version: '3'

tasks:
  default:
    deps: [mock, graphql]
    desc: Run default tasks

  mock:
    aliases: [m]
    desc: Generate mock files
    cmds:
      - go install github.com/matryer/moq@latest
      - moq -out pkg/domain/mock/interfaces.go -pkg mock ./pkg/domain/interfaces SlackClient ThreadRepository HistoryRepository StorageAdapter
    sources:
      - pkg/domain/interfaces/*.go
    generates:
      - pkg/domain/mock/interfaces.go

  graphql:
    aliases: [g]
    desc: Generate GraphQL code
    cmds:
      - go install github.com/99designs/gqlgen@latest
      - go run github.com/99designs/gqlgen generate
    sources:
      - gqlgen.yml
      - graphql/*.graphql
    generates:
      - pkg/controller/graphql/generated.go
      - pkg/domain/model/graphql/models_gen.go
      - pkg/controller/graphql/schema.resolvers.go

  test:
    aliases: [t]
    desc: Run all tests
    cmds:
      - go test ./...

  vet:
    aliases: [v]
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    aliases: [l]
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  gosec:
    aliases: [s]
    desc: Run gosec security scanner
    cmds:
      - gosec -exclude-generated -quiet ./...

  check:
    aliases: [c]
    desc: Run all checks (test, vet, lint, gosec)
    deps:
      - test
      - vet
      - lint
      - gosec