// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/m-mizutani/tamamo/pkg/domain/model/slack"
)

type Query struct {
}

type ThreadsResponse struct {
	Threads    []*slack.Thread `json:"threads"`
	TotalCount int             `json:"totalCount"`
}
